allowBuilds:
  '@parcel/watcher': false
  bcrypt: false
  esbuild: false
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - bcrypt
  - esbuild
  - sharp
  - unrs-resolver
